Global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: strict
ipv6: false
log-level: debug
geo-auto-update: true
geo-update-interval: 168
secret: ''
bind-address: '*'
unified-delay: false
disable-keep-alive: false
keep-alive-idle: 30
keep-alive-interval: 30
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  respect-rules: false
  prefer-h3: false
  cache-algorithm: arc
  use-system-hosts: true
  use-host: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.localdomain'
  - '*.invalid'
  - '*.localhost'
  - '*.test'
  - '*.local'
  - '*.home.arpa'
  - time.*.com
  - ntp.*.com
  - '*.ir'
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - 1.0.0.1
  - 1.1.1.1
  - 9.9.9.9
  - 9.9.9.11
  - 9.9.9.10
  - 94.140.14.15
  - 94.140.15.15
  - 223.5.5.5
  - 77.88.8.8
  - 208.67.222.222
  - 208.67.220.220
  - 209.244.0.3
  - 209.224.0.4
  - 74.82.42.42
  nameserver:
  - https://dns.nextdns.io/15441b
  - tls://15441b.dns.nextdns.io
  direct-nameserver:
  - 78.157.42.100
  - 78.157.42.101
  proxy-server-nameserver:
  - 1.1.1.1
  - 8.8.8.8
  - 8.8.4.4
  - 9.9.9.9
  - 223.5.5.5
  - 77.88.8.8
  - 208.67.222.222
  - 208.67.220.220
  - 209.244.0.3
  - 209.224.0.4
  - 74.82.42.42
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  auto-redir: true
  dns-hijack:
  - any:53
  - tcp://any:53
proxies:
- name: ğŸ‡¨ğŸ‡¦ Anon8
  type: wireguard
  server: 188.114.96.172
  port: 1014
  private-key: +PKqyWtT0G14ecvjTFt+9UZqmrK0F/o3EiLh+sW+/2c=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 45
  - 90
  - 159
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ $$$+jadid+ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey
  type: wireguard
  server: 188.114.97.227
  port: 7156
  private-key: 0M+HdI1UAxACTEm5/KJ+HTAuro4BZkyAvHsQC3l2pn0=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 126
  - 90
  - 140
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ mci jadid ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey
  type: wireguard
  server: 188.114.98.12
  port: 1002
  private-key: 0M+HdI1UAxACTEm5/KJ+HTAuro4BZkyAvHsQC3l2pn0=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 126
  - 90
  - 140
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Anon5
  type: wireguard
  server: 188.114.98.68
  port: 945
  private-key: GAQOBNPwbXpuMZP0tEZtjeWz9gW6YwCYiZp95Yb+gVQ=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 156
  - 192
  - 14
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Peyman_wire-g
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: GJqSVBur83GBVwmO4Bq7GPu59pXy5JF9/MW7u2/p41s=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:879a:8bb4:d3b3:d538:bae7/128
  reserved:
  - 211
  - 148
  - 56
  mtu: 1420
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Peyman_wire-g-2
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: H+Qmpej6un84cv6pIjqntkQOqzM6QxrqJ89CVvgZQPI=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:837b:5be8:e1a1:a455:b585/128
  reserved:
  - 41
  - 229
  - 34
  mtu: 1420
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Peyman_wire-g-3
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: J5rjU1kn1eQUBAhJstmG/4QHbtUhbpxr640uO8OeFTk=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8b03:530e:fffb:cee8:640b/128
  reserved:
  - 206
  - 54
  - 234
  mtu: 1420
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ @An0nymousteam - W4
  type: wireguard
  server: 188.114.98.224
  port: 2408
  private-key: MHdFJ6p42DHy5b2tQ6pD/b00Xtqbvsq4kN6GRaXAHUQ=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:83fa:553:b178:9afd:d3b0/128
  reserved:
  - 0
  - 0
  - 0
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ @An0nymousteam - W5
  type: wireguard
  server: 188.114.98.224
  port: 2408
  private-key: MHdFJ6p42DHy5b2tQ6pD/b00Xtqbvsq4kN6GRaXAHUQ=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:83fa:553:b178:9afd:d3b0/128
  reserved:
  - 0
  - 0
  - 0
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Peyman_wire-g-4
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: OV4B2f1lIsZM1WNFA6PzlPYWvjz3DBagBZrGI2pA9WQ=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8ab0:4a02:2465:b3b3:3974/128
  reserved:
  - 239
  - 4
  - 47
  mtu: 1420
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ jadid+ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey
  type: wireguard
  server: 188.114.96.16
  port: 4233
  private-key: QKRFk8I+jwBi4WlpjC1a75bb7oQGmHQnYfw0rThENEk=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 244
  - 100
  - 79
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ @freeiranianv2rey+ğŸ’¯ğŸ’¯ğŸ’¯ØªØ§+Ø§Ø¨Ø¯+Ø±Ø§ÛŒÚ¯Ø§Ù†
  type: wireguard
  server: 188.114.96.49
  port: 864
  private-key: QKRFk8I+jwBi4WlpjC1a75bb7oQGmHQnYfw0rThENEk=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 244
  - 100
  - 79
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Ù¾Ø±Ù‚Ø¯Ø±Øª@freeiranianv2rey
  type: wireguard
  server: 188.114.97.239
  port: 908
  private-key: QKRFk8I+jwBi4WlpjC1a75bb7oQGmHQnYfw0rThENEk=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 244
  - 100
  - 79
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Peyman_wire-g-5
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: RZ3JzNczJ61pKEFdS5zRtAd99RVnI3z5VjnEuu52J6E=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:83b5:c2c0:6c1c:daa:bfb/128
  reserved:
  - 105
  - 83
  - 197
  mtu: 1420
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Anon10
  type: wireguard
  server: 188.114.98.46
  port: 942
  private-key: SG3Qs61uoQHLcyaLiQcXGf5Y2SvGbhgbVKbF3XwWMWI=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 3
  - 173
  - 201
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Peyman_wire-g-6
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: VDxVxWQ+vQHY4BnjS+XCamUtGZ+yPt3YUQITafJgk+c=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:84ee:6009:17fb:e751:3a4b/128
  reserved:
  - 67
  - 93
  - 163
  mtu: 1420
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Peyman_wire-g-7
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: VPJHv3WABigVVb//k0BivH3mhQNVIgkWzTK1I7k24+I=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8f89:650f:181:6757:78dd/128
  reserved:
  - 57
  - 119
  - 188
  mtu: 1420
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Peyman_wire-g-8
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: aTeYaof4wPqHzJ+GBXk5TIwoWKvobmeAGswy82bOVxI=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8909:a282:cd79:40d:e673/128
  reserved:
  - 218
  - 227
  - 185
  mtu: 1420
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Peyman_wire-g-9
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: e8bPN+F/yffsy65NmH7/a/EC+VXVHLuJmmMJ8+f45Qs=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8f59:aaa9:47d8:d66e:eaa2/128
  reserved:
  - 91
  - 5
  - 110
  mtu: 1420
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡ºğŸ‡¸ Anon9
  type: wireguard
  server: 188.114.99.20
  port: 988
  private-key: gGGQ9BSc43wn9N3RLVDJc9+uN5Au0Me0kGt5NBsRvmg=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 68
  - 46
  - 65
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡ºğŸ‡¸ Anon4
  type: wireguard
  server: 188.114.99.77
  port: 1002
  private-key: gIauKnNzXKMWEKvB+sHgqsuvuRgH8znnV7zGOBwrG1c=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 100
  - 90
  - 121
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡ºğŸ‡¸ Anon6
  type: wireguard
  server: 188.114.99.162
  port: 945
  private-key: gO8yVa81i3qwTA3jF5SGaJvsUmB/VNpGoLUMKfMsW3Y=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 134
  - 227
  - 39
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡ºğŸ‡¸ Anon3
  type: wireguard
  server: 188.114.99.13
  port: 1014
  private-key: oHuAPQ+Zp27PIW9rCfVhC67cRF4hmQslv02RsvRKJFA=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 131
  - 10
  - 229
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Anon2
  type: wireguard
  server: 188.114.96.13
  port: 880
  private-key: oO1w9zWoj855k41EX5KeM1jCidPjSJtgMLSxnMKLW1M=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 41
  - 201
  - 247
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Peyman_wire-g-10
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: pQDbEYtlraysU6wwgqF1/E3iV2pIwINF6fSGzQBlC9U=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8722:b351:ead1:45a0:3147/128
  reserved:
  - 243
  - 85
  - 37
  mtu: 1420
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Anon1
  type: wireguard
  server: 188.114.97.240
  port: 908
  private-key: qPvJ0+mwPeeY0I5APw6FSf4I1EOiMkRw36RdLiInpVY=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 51
  - 195
  - 74
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
- name: ğŸ‡¨ğŸ‡¦ Anon7
  type: wireguard
  server: 188.114.96.23
  port: 945
  private-key: wDgEhNfjrpuiuGDgfQWpYvq27Rjyjj3eqTTx5n/gL28=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  reserved:
  - 240
  - 34
  - 6
  mtu: 1280
  allowed-ips:
  - 0.0.0.0/0
  - ::/0
proxy-groups:
- name: Ù†ÙˆØ¹ Ø§Ù†ØªØ®Ø§Ø¨ Ù¾Ø±ÙˆÚ©Ø³ÛŒ ğŸ”€
  icon: https://www.svgrepo.com/show/412721/choose.svg
  type: select
  proxies:
  - Ø®ÙˆØ¯Ú©Ø§Ø± (Ø¨Ù‡ØªØ±ÛŒÙ† Ù¾ÛŒÙ†Ú¯) ğŸ¤–
  - Ø¯Ø³ØªÛŒ ğŸ¤ğŸ»
  - Ù¾Ø´ØªÛŒØ¨Ø§Ù† (Ø¯Ø± ØµÙˆØ±Øª Ù‚Ø·Ø¹ÛŒ) ğŸ§¯
  - Ø¨Ø¯ÙˆÙ† ÙÛŒÙ„ØªØ±Ø´Ú©Ù† ğŸ›¡ï¸
- name: Ø¯Ø³ØªÛŒ ğŸ¤ğŸ»
  type: select
  icon: https://www.svgrepo.com/show/372331/cursor-hand-click.svg
  proxies:
  - ğŸ‡¨ğŸ‡¦ Anon8
  - ğŸ‡¨ğŸ‡¦ $$$+jadid+ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey
  - ğŸ‡¨ğŸ‡¦ mci jadid ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey
  - ğŸ‡¨ğŸ‡¦ Anon5
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-2
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-3
  - ğŸ‡¨ğŸ‡¦ @An0nymousteam - W4
  - ğŸ‡¨ğŸ‡¦ @An0nymousteam - W5
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-4
  - ğŸ‡¨ğŸ‡¦ jadid+ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey
  - ğŸ‡¨ğŸ‡¦ @freeiranianv2rey+ğŸ’¯ğŸ’¯ğŸ’¯ØªØ§+Ø§Ø¨Ø¯+Ø±Ø§ÛŒÚ¯Ø§Ù†
  - ğŸ‡¨ğŸ‡¦ Ù¾Ø±Ù‚Ø¯Ø±Øª@freeiranianv2rey
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-5
  - ğŸ‡¨ğŸ‡¦ Anon10
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-6
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-7
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-8
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-9
  - ğŸ‡ºğŸ‡¸ Anon9
  - ğŸ‡ºğŸ‡¸ Anon4
  - ğŸ‡ºğŸ‡¸ Anon6
  - ğŸ‡ºğŸ‡¸ Anon3
  - ğŸ‡¨ğŸ‡¦ Anon2
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-10
  - ğŸ‡¨ğŸ‡¦ Anon1
  - ğŸ‡¨ğŸ‡¦ Anon7
- name: Ø®ÙˆØ¯Ú©Ø§Ø± (Ø¨Ù‡ØªØ±ÛŒÙ† Ù¾ÛŒÙ†Ú¯) ğŸ¤–
  type: url-test
  icon: https://www.svgrepo.com/show/7876/speedometer.svg
  url: https://api.v2fly.org/checkConnection.svgz
  interval: 600
  timeout: 120000
  tolerance: 500
  lazy: true
  proxies:
  - ğŸ‡¨ğŸ‡¦ Anon8
  - ğŸ‡¨ğŸ‡¦ $$$+jadid+ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey
  - ğŸ‡¨ğŸ‡¦ mci jadid ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey
  - ğŸ‡¨ğŸ‡¦ Anon5
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-2
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-3
  - ğŸ‡¨ğŸ‡¦ @An0nymousteam - W4
  - ğŸ‡¨ğŸ‡¦ @An0nymousteam - W5
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-4
  - ğŸ‡¨ğŸ‡¦ jadid+ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey
  - ğŸ‡¨ğŸ‡¦ @freeiranianv2rey+ğŸ’¯ğŸ’¯ğŸ’¯ØªØ§+Ø§Ø¨Ø¯+Ø±Ø§ÛŒÚ¯Ø§Ù†
  - ğŸ‡¨ğŸ‡¦ Ù¾Ø±Ù‚Ø¯Ø±Øª@freeiranianv2rey
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-5
  - ğŸ‡¨ğŸ‡¦ Anon10
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-6
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-7
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-8
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-9
  - ğŸ‡ºğŸ‡¸ Anon9
  - ğŸ‡ºğŸ‡¸ Anon4
  - ğŸ‡ºğŸ‡¸ Anon6
  - ğŸ‡ºğŸ‡¸ Anon3
  - ğŸ‡¨ğŸ‡¦ Anon2
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-10
  - ğŸ‡¨ğŸ‡¦ Anon1
  - ğŸ‡¨ğŸ‡¦ Anon7
- name: Ù¾Ø´ØªÛŒØ¨Ø§Ù† (Ø¯Ø± ØµÙˆØ±Øª Ù‚Ø·Ø¹ÛŒ) ğŸ§¯
  type: fallback
  icon: https://www.svgrepo.com/show/415208/backup-cloud-document.svg
  url: https://www.gstatic.com/generate_204
  interval: 600
  timeout: 120000
  lazy: true
  proxies:
  - ğŸ‡¨ğŸ‡¦ Anon8
  - ğŸ‡¨ğŸ‡¦ $$$+jadid+ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey
  - ğŸ‡¨ğŸ‡¦ mci jadid ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey
  - ğŸ‡¨ğŸ‡¦ Anon5
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-2
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-3
  - ğŸ‡¨ğŸ‡¦ @An0nymousteam - W4
  - ğŸ‡¨ğŸ‡¦ @An0nymousteam - W5
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-4
  - ğŸ‡¨ğŸ‡¦ jadid+ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey
  - ğŸ‡¨ğŸ‡¦ @freeiranianv2rey+ğŸ’¯ğŸ’¯ğŸ’¯ØªØ§+Ø§Ø¨Ø¯+Ø±Ø§ÛŒÚ¯Ø§Ù†
  - ğŸ‡¨ğŸ‡¦ Ù¾Ø±Ù‚Ø¯Ø±Øª@freeiranianv2rey
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-5
  - ğŸ‡¨ğŸ‡¦ Anon10
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-6
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-7
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-8
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-9
  - ğŸ‡ºğŸ‡¸ Anon9
  - ğŸ‡ºğŸ‡¸ Anon4
  - ğŸ‡ºğŸ‡¸ Anon6
  - ğŸ‡ºğŸ‡¸ Anon3
  - ğŸ‡¨ğŸ‡¦ Anon2
  - ğŸ‡¨ğŸ‡¦ Peyman_wire-g-10
  - ğŸ‡¨ğŸ‡¦ Anon1
  - ğŸ‡¨ğŸ‡¦ Anon7
- name: ØªÙ„Ú¯Ø±Ø§Ù… ğŸ’¬
  type: select
  icon: https://www.svgrepo.com/show/354443/telegram.svg
  proxies:
  - Ù†ÙˆØ¹ Ø§Ù†ØªØ®Ø§Ø¨ Ù¾Ø±ÙˆÚ©Ø³ÛŒ ğŸ”€
  - Ø¨Ø¯ÙˆÙ† ÙÛŒÙ„ØªØ±Ø´Ú©Ù† ğŸ›¡ï¸
  - Ø®ÙˆØ¯Ú©Ø§Ø± (Ø¨Ù‡ØªØ±ÛŒÙ† Ù¾ÛŒÙ†Ú¯) ğŸ¤–
  - Ø¯Ø³ØªÛŒ ğŸ¤ğŸ»
  - Ù¾Ø´ØªÛŒØ¨Ø§Ù† (Ø¯Ø± ØµÙˆØ±Øª Ù‚Ø·Ø¹ÛŒ) ğŸ§¯
  - Ø§Ø¬Ø§Ø²Ù‡ Ù†Ø¯Ø§Ø¯Ù† ğŸš«
- name: Ø³Ø§ÛŒØªØ§ÛŒ Ø§ÛŒØ±Ø§Ù†ÛŒ ğŸ‡®ğŸ‡·
  type: select
  icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Iran_%28civil%29.svg
  proxies:
  - Ø¨Ø¯ÙˆÙ† ÙÛŒÙ„ØªØ±Ø´Ú©Ù† ğŸ›¡ï¸
  - Ø§Ø¬Ø§Ø²Ù‡ Ù†Ø¯Ø§Ø¯Ù† ğŸš«
  - Ù†ÙˆØ¹ Ø§Ù†ØªØ®Ø§Ø¨ Ù¾Ø±ÙˆÚ©Ø³ÛŒ ğŸ”€
  - Ø®ÙˆØ¯Ú©Ø§Ø± (Ø¨Ù‡ØªØ±ÛŒÙ† Ù¾ÛŒÙ†Ú¯) ğŸ¤–
  - Ø¯Ø³ØªÛŒ ğŸ¤ğŸ»
  - Ù¾Ø´ØªÛŒØ¨Ø§Ù† (Ø¯Ø± ØµÙˆØ±Øª Ù‚Ø·Ø¹ÛŒ) ğŸ§¯
- name: Ø¨Ø¯ÙˆÙ† ÙÛŒÙ„ØªØ±Ø´Ú©Ù† ğŸ›¡ï¸
  type: select
  icon: https://www.svgrepo.com/show/6318/connection.svg
  proxies:
  - DIRECT
  hidden: true
- name: Ø§Ø¬Ø§Ø²Ù‡ Ù†Ø¯Ø§Ø¯Ù† ğŸš«
  type: select
  icon: https://www.svgrepo.com/show/444307/gui-ban.svg
  proxies:
  - REJECT
  hidden: true
rule-providers:
  apps:
    type: http
    format: yaml
    behavior: classical
    url: https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/apps.yaml
    path: ./ruleset/apps.yaml
    interval: 86400
rules:
- PROCESS-NAME,Telegram.exe,ØªÙ„Ú¯Ø±Ø§Ù… ğŸ’¬
- PROCESS-NAME,org.telegram.messenger,ØªÙ„Ú¯Ø±Ø§Ù… ğŸ’¬
- PROCESS-NAME,org.telegram.messenger.web,ØªÙ„Ú¯Ø±Ø§Ù… ğŸ’¬
- DOMAIN-SUFFIX,ir,Ø³Ø§ÛŒØªØ§ÛŒ Ø§ÛŒØ±Ø§Ù†ÛŒ ğŸ‡®ğŸ‡·
- GEOIP,ir,Ø³Ø§ÛŒØªØ§ÛŒ Ø§ÛŒØ±Ø§Ù†ÛŒ ğŸ‡®ğŸ‡·
- IP-CIDR,10.10.34.0/24,Ù†ÙˆØ¹ Ø§Ù†ØªØ®Ø§Ø¨ Ù¾Ø±ÙˆÚ©Ø³ÛŒ ğŸ”€
- RULE-SET,apps,Ø³Ø§ÛŒØªØ§ÛŒ Ø§ÛŒØ±Ø§Ù†ÛŒ ğŸ‡®ğŸ‡·
- MATCH,Ù†ÙˆØ¹ Ø§Ù†ØªØ®Ø§Ø¨ Ù¾Ø±ÙˆÚ©Ø³ÛŒ ğŸ”€
ntp:
  enable: true
  server: time.apple.com
  port: 123
  interval: 30
