Global-client-fingerprint: chrome
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
tcp-concurrent: true
enable-process: true
find-process-mode: strict
ipv6: false
log-level: debug
geo-auto-update: true
geo-update-interval: 168
secret: ''
bind-address: '*'
unified-delay: false
disable-keep-alive: false
keep-alive-idle: 30
keep-alive-interval: 30
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  respect-rules: false
  prefer-h3: false
  cache-algorithm: arc
  use-system-hosts: true
  use-host: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.localdomain'
  - '*.invalid'
  - '*.localhost'
  - '*.test'
  - '*.local'
  - '*.home.arpa'
  - time.*.com
  - ntp.*.com
  - '*.ir'
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
  - 1.0.0.1
  - 1.1.1.1
  - 9.9.9.9
  - 9.9.9.11
  - 9.9.9.10
  - 94.140.14.15
  - 94.140.15.15
  - 223.5.5.5
  - 77.88.8.8
  - 208.67.222.222
  - 208.67.220.220
  - 209.244.0.3
  - 209.224.0.4
  - 74.82.42.42
  nameserver:
  - https://dns.nextdns.io/15441b
  - tls://15441b.dns.nextdns.io
  direct-nameserver:
  - 78.157.42.100
  - 78.157.42.101
  proxy-server-nameserver:
  - 1.1.1.1
  - 8.8.8.8
  - 8.8.4.4
  - 9.9.9.9
  - 223.5.5.5
  - 77.88.8.8
  - 208.67.222.222
  - 208.67.220.220
  - 209.244.0.3
  - 209.224.0.4
  - 74.82.42.42
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  auto-redir: true
  dns-hijack:
  - any:53
  - tcp://any:53
proxies:
- name: '[WIREGUARD] ğŸ³ï¸ Anon9'
  type: wireguard
  server: 188.114.96.172
  port: 1014
  private-key: +PKqyWtT0G14ecvjTFt+9UZqmrK0F/o3EiLh+sW+/2c=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ³ï¸ $$$+jadid+ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey'
  type: wireguard
  server: 188.114.97.227
  port: 7156
  private-key: 0M+HdI1UAxACTEm5/KJ+HTAuro4BZkyAvHsQC3l2pn0=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ‡¨ğŸ‡¦ mci jadid ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey'
  type: wireguard
  server: 188.114.98.12
  port: 1002
  private-key: 0M+HdI1UAxACTEm5/KJ+HTAuro4BZkyAvHsQC3l2pn0=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ³ï¸ Peyman_wire-g'
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: 1AzrQclQQlWkI30tJE3DoHvF+UeWdV71QVCtRmlsl3o=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8766:b13b:8da5:6784:b396/128
  mtu: 1420
- name: '[WIREGUARD] ğŸ³ï¸ Peyman_wire-g-2'
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: Ce93JYt2qU7B2cMAz1sVi0llpgq0JTA7Er8T8mUJvN0=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8632:7c3:7451:b265:6f42/128
  mtu: 1420
- name: '[WIREGUARD] ğŸ³ï¸ Peyman_wire-g-3'
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: ErSc+mMSjYmNXEmtZ9PU2s+/10vwYAkw8GcdZ6H8UjY=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8d7d:568f:5dc6:93b2:e7d9/128
  mtu: 1420
- name: '[WIREGUARD] ğŸ³ï¸ Peyman_wire-g-4'
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: Fh1jqiQn5QC4a9yojM2Gu1ehRi+iEeb4LZbLBybG7EQ=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8c84:6c1a:79e8:a9a5:18d6/128
  mtu: 1420
- name: '[WIREGUARD] ğŸ‡¨ğŸ‡¦ Anon6'
  type: wireguard
  server: 188.114.98.68
  port: 945
  private-key: GAQOBNPwbXpuMZP0tEZtjeWz9gW6YwCYiZp95Yb+gVQ=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ‡ºğŸ‡¸ Anon1'
  type: wireguard
  server: 188.114.99.209
  port: 942
  private-key: IBMHSrdMjVoo/25L+k7aSLLuF/vZG46jA5I+nti0404=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ³ï¸ Peyman_wire-g-5'
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: IlQ+wueN9CkZi3QWYk52H5kicy6nUBvdEnJbP79++n8=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:852b:4fc8:50e0:ca12:feca/128
  mtu: 1420
- name: '[WIREGUARD] ğŸ³ï¸ Peyman_wire-g-6'
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: KGPdd6x2nZzkEEumV97Og1cQHDgZvw7Nrx5UKplR9go=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8904:ddac:8420:98b5:8961/128
  mtu: 1420
- name: '[WIREGUARD] ğŸ³ï¸ Peyman_wire-g-7'
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: OHuxsVOhLEdHxvgv8jUqPD1sWLZGSycNbL/0xCo/xAk=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8a0c:3c99:8a5e:4bf5:d1ac/128
  mtu: 1420
- name: '[WIREGUARD] ğŸ³ï¸ jadid+ğŸ’ªğŸ’ªğŸ’ª@freeiranianv2rey'
  type: wireguard
  server: 188.114.96.16
  port: 4233
  private-key: QKRFk8I+jwBi4WlpjC1a75bb7oQGmHQnYfw0rThENEk=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ‡¨ğŸ‡¦ @freeiranianv2rey+ğŸ’¯ğŸ’¯ğŸ’¯ØªØ§+Ø§Ø¨Ø¯+Ø±Ø§ÛŒÚ¯Ø§Ù†'
  type: wireguard
  server: 188.114.96.49
  port: 864
  private-key: QKRFk8I+jwBi4WlpjC1a75bb7oQGmHQnYfw0rThENEk=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ³ï¸ Ù¾Ø±Ù‚Ø¯Ø±Øª@freeiranianv2rey'
  type: wireguard
  server: 188.114.97.239
  port: 908
  private-key: QKRFk8I+jwBi4WlpjC1a75bb7oQGmHQnYfw0rThENEk=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ³ï¸ 2606:4700:d0::d91:179:c651:ed70'
  type: wireguard
  server: 2606:4700:d0::d91:179:c651:ed70
  port: 7281
  private-key: QKRFk8I+jwBi4WlpjC1a75bb7oQGmHQnYfw0rThENEk=
  public-key: p6+zdc6L4w2uG51zEq7/G79eR2s/2Dl0P3bh1TBIkA0=
  udp: true
- name: '[WIREGUARD] ğŸ³ï¸ Peyman_wire-g-8'
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: UkUxAAyimA57C4JQ08utIIZ/AxYu9iV32lkLbxbz97Q=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:84c4:320c:a96:a1da:7d3a/128
  mtu: 1420
- name: '[WIREGUARD] ğŸ³ï¸ Peyman_wire-g-9'
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: VQO9qKv4uSHaEBL94AXd6VBXFJVBxp+egf9Qa9SiE8A=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8f02:6e90:a84c:12b6:3d1e/128
  mtu: 1420
- name: '[WIREGUARD] ğŸ‡ºğŸ‡¸ Anon10'
  type: wireguard
  server: 188.114.99.20
  port: 988
  private-key: gGGQ9BSc43wn9N3RLVDJc9+uN5Au0Me0kGt5NBsRvmg=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ³ï¸ Anon5'
  type: wireguard
  server: 188.114.99.77
  port: 1002
  private-key: gIauKnNzXKMWEKvB+sHgqsuvuRgH8znnV7zGOBwrG1c=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ³ï¸ Anon7'
  type: wireguard
  server: 188.114.99.162
  port: 945
  private-key: gO8yVa81i3qwTA3jF5SGaJvsUmB/VNpGoLUMKfMsW3Y=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ³ï¸ Peyman_wire-g-10'
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  private-key: oGN1K0RyCXj6vOoA0xsIUrf0hpulqIE+ECb3wmLZUdg=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  ipv6: 2606:4700:110:8705:82be:68ba:df9f:4924/128
  mtu: 1420
- name: '[WIREGUARD] ğŸ‡ºğŸ‡¸ Anon4'
  type: wireguard
  server: 188.114.99.13
  port: 1014
  private-key: oHuAPQ+Zp27PIW9rCfVhC67cRF4hmQslv02RsvRKJFA=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ³ï¸ Anon3'
  type: wireguard
  server: 188.114.96.13
  port: 880
  private-key: oO1w9zWoj855k41EX5KeM1jCidPjSJtgMLSxnMKLW1M=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ‡¨ğŸ‡¦ Anon2'
  type: wireguard
  server: 188.114.97.240
  port: 908
  private-key: qPvJ0+mwPeeY0I5APw6FSf4I1EOiMkRw36RdLiInpVY=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
- name: '[WIREGUARD] ğŸ‡¨ğŸ‡¦ Anon8'
  type: wireguard
  server: 188.114.96.23
  port: 945
  private-key: wDgEhNfjrpuiuGDgfQWpYvq27Rjyjj3eqTTx5n/gL28=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  ip: 172.16.0.2/32
  mtu: 1280
proxy-groups:
- name: Ù†ÙˆØ¹ Ø§Ù†ØªØ®Ø§Ø¨ Ù¾Ø±ÙˆÚ©Ø³ÛŒ ğŸ”€
  icon: https://www.svgrepo.com/show/412721/choose.svg
  type: select
  proxies:
  - Ø®ÙˆØ¯Ú©Ø§Ø± (Ø¨Ù‡ØªØ±ÛŒÙ† Ù¾ÛŒÙ†Ú¯) ğŸ¤–
  - Ø¯Ø³ØªÛŒ ğŸ¤ğŸ»
  - Ù¾Ø´ØªÛŒØ¨Ø§Ù† (Ø¯Ø± ØµÙˆØ±Øª Ù‚Ø·Ø¹ÛŒ) ğŸ§¯
  - Ø¨Ø¯ÙˆÙ† ÙÛŒÙ„ØªØ±Ø´Ú©Ù† ğŸ›¡ï¸
- name: Ø¯Ø³ØªÛŒ ğŸ¤ğŸ»
  type: select
  icon: https://www.svgrepo.com/show/372331/cursor-hand-click.svg
  proxies:
  - ALL_PROXIES_PLACEHOLDER
- name: Ø®ÙˆØ¯Ú©Ø§Ø± (Ø¨Ù‡ØªØ±ÛŒÙ† Ù¾ÛŒÙ†Ú¯) ğŸ¤–
  type: url-test
  icon: https://www.svgrepo.com/show/7876/speedometer.svg
  url: https://api.v2fly.org/checkConnection.svgz
  interval: 360000
  timeout: 120000
  tolerance: 10
  lazy: true
  proxies:
  - ALL_PROXIES_PLACEHOLDER
- name: Ù¾Ø´ØªÛŒØ¨Ø§Ù† (Ø¯Ø± ØµÙˆØ±Øª Ù‚Ø·Ø¹ÛŒ) ğŸ§¯
  type: fallback
  icon: https://www.svgrepo.com/show/415208/backup-cloud-document.svg
  url: https://www.gstatic.com/generate_204
  interval: 360000
  timeout: 120000
  tolerance: 6
  lazy: true
  proxies:
  - ALL_PROXIES_PLACEHOLDER
- name: ØªÙ„Ú¯Ø±Ø§Ù… ğŸ’¬
  type: select
  icon: https://www.svgrepo.com/show/354443/telegram.svg
  proxies:
  - Ù†ÙˆØ¹ Ø§Ù†ØªØ®Ø§Ø¨ Ù¾Ø±ÙˆÚ©Ø³ÛŒ ğŸ”€
  - Ø¨Ø¯ÙˆÙ† ÙÛŒÙ„ØªØ±Ø´Ú©Ù† ğŸ›¡ï¸
  - Ø®ÙˆØ¯Ú©Ø§Ø± (Ø¨Ù‡ØªØ±ÛŒÙ† Ù¾ÛŒÙ†Ú¯) ğŸ¤–
  - Ø¯Ø³ØªÛŒ ğŸ¤ğŸ»
  - Ù¾Ø´ØªÛŒØ¨Ø§Ù† (Ø¯Ø± ØµÙˆØ±Øª Ù‚Ø·Ø¹ÛŒ) ğŸ§¯
  - Ø§Ø¬Ø§Ø²Ù‡ Ù†Ø¯Ø§Ø¯Ù† ğŸš«
- name: Ø³Ø§ÛŒØªØ§ÛŒ Ø§ÛŒØ±Ø§Ù†ÛŒ ğŸ‡®ğŸ‡·
  type: select
  icon: https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Iran_%28civil%29.svg
  proxies:
  - Ø¨Ø¯ÙˆÙ† ÙÛŒÙ„ØªØ±Ø´Ú©Ù† ğŸ›¡ï¸
  - Ø§Ø¬Ø§Ø²Ù‡ Ù†Ø¯Ø§Ø¯Ù† ğŸš«
  - Ù†ÙˆØ¹ Ø§Ù†ØªØ®Ø§Ø¨ Ù¾Ø±ÙˆÚ©Ø³ÛŒ ğŸ”€
  - Ø®ÙˆØ¯Ú©Ø§Ø± (Ø¨Ù‡ØªØ±ÛŒÙ† Ù¾ÛŒÙ†Ú¯) ğŸ¤–
  - Ø¯Ø³ØªÛŒ ğŸ¤ğŸ»
  - Ù¾Ø´ØªÛŒØ¨Ø§Ù† (Ø¯Ø± ØµÙˆØ±Øª Ù‚Ø·Ø¹ÛŒ) ğŸ§¯
- name: Ø¨Ø¯ÙˆÙ† ÙÛŒÙ„ØªØ±Ø´Ú©Ù† ğŸ›¡ï¸
  type: select
  icon: https://www.svgrepo.com/show/6318/connection.svg
  proxies:
  - DIRECT
  hidden: true
- name: Ø§Ø¬Ø§Ø²Ù‡ Ù†Ø¯Ø§Ø¯Ù† ğŸš«
  type: select
  icon: https://www.svgrepo.com/show/444307/gui-ban.svg
  proxies:
  - REJECT
  hidden: true
rule-providers:
  apps:
    type: http
    format: yaml
    behavior: classical
    url: https://github.com/chocolate4u/Iran-clash-rules/releases/latest/download/apps.yaml
    path: ./ruleset/apps.yaml
    interval: 86400
rules:
- PROCESS-NAME,Telegram.exe,ØªÙ„Ú¯Ø±Ø§Ù… ğŸ’¬
- PROCESS-NAME,org.telegram.messenger,ØªÙ„Ú¯Ø±Ø§Ù… ğŸ’¬
- PROCESS-NAME,org.telegram.messenger.web,ØªÙ„Ú¯Ø±Ø§Ù… ğŸ’¬
- DOMAIN-SUFFIX,ir,Ø³Ø§ÛŒØªØ§ÛŒ Ø§ÛŒØ±Ø§Ù†ÛŒ ğŸ‡®ğŸ‡·
- GEOIP,ir,Ø³Ø§ÛŒØªØ§ÛŒ Ø§ÛŒØ±Ø§Ù†ÛŒ ğŸ‡®ğŸ‡·
- IP-CIDR,10.10.34.0/24,Ù†ÙˆØ¹ Ø§Ù†ØªØ®Ø§Ø¨ Ù¾Ø±ÙˆÚ©Ø³ÛŒ ğŸ”€
- RULE-SET,apps,Ø³Ø§ÛŒØªØ§ÛŒ Ø§ÛŒØ±Ø§Ù†ÛŒ ğŸ‡®ğŸ‡·
- MATCH,Ù†ÙˆØ¹ Ø§Ù†ØªØ®Ø§Ø¨ Ù¾Ø±ÙˆÚ©Ø³ÛŒ ğŸ”€
ntp:
  enable: true
  server: time.apple.com
  port: 123
  interval: 30
